version: '3.3'

services:
  microservice-module:
    image: microservice-module:latest
    container_name: microservice-module
    ports:
      - 8080:8080
    networks:
      - microservice-personaldata_footforward-network
    external_links:
      - microservice-personaldata
      - microservice-note
      - microservice-risk
    restart: always

networks:
  microservice-personaldata_footforward-network:
    driver: bridge
    external: true
