version: '3.3'

services:
  microservice-risk:
    image: microservice-risk:latest
    container_name: microservice-risk
    ports:
      - 9003:9003
    networks:
      - microservice-personaldata_footforward-network
    external_links:
      - microservice-personaldata
      - microservice-note

    restart: always

networks:
  microservice-personaldata_footforward-network:
    driver: bridge
    external: true
