version: '3.3'

services:
  mysqlcontainer:
    container_name: mysqlcontainer
    image: mysql:latest

    environment:
        MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
    secrets:
          - db_password
    volumes:
      - ../../data/db:/var/lib/mysql

    ports:
      - "3306:3306"
    networks:
      - footforward-network
    restart: always


  microservice-personaldata:
    image: microservice-personaldata:latest
    container_name: microservice-personaldata
    ports:
      - 9001:9001
    networks:
      - footforward-network
    depends_on:
      - mysqlcontainer
    restart: always
secrets:
  db_password:
    file: ./secrets/db_password.txt

networks:
  footforward-network:
    driver: bridge
